module.exports = {
  prison: {
    jailCapSeconds: 86400,
    minJailSeconds: 300,
    defaultJailSeconds: 3600,
    bailBase: 25000,
    bailPerBlock: 5000,
    bailBlockSeconds: 300,
    bailMultiplier: 1,
    breakoutPenaltySeconds: 180,
    breakoutAssistEnabled: true,
    breakoutBaseChance: 0.35,
    breakoutLevelBonus: 0.01,
    breakoutPenaltyCapSeconds: 1800,
  },
  hospital: {
    hospitalCapSeconds: 86400,
    minHospitalSeconds: 120,
    defaultHospitalSeconds: 900,
    treatSeconds: 180,
    treatHealthPerSecond: 0.4,
    reviveBase: 20000,
    revivePerBlock: 4000,
    reviveBlockSeconds: 300,
    reviveLevelFactor: 500,
    reviveHealthFloor: 150,
    allowPaidRevive: true,
  },
  crime: {
    enableHealthLoss: true,
    criticalHpLossPercent: 25,
    criticalHpLossFlat: 0,
    severityMultipliers: {
      minor: 0.6,
      moderate: 1,
      major: 1.4,
    },
    enableHospitalize: true,
    hospitalSeconds: 900,
    hospitalVarianceSeconds: 120,
    hospitalHealthFloor: 35,
    hospitalizeBelowHealth: 20,
    enableJail: true,
    jailChancePercent: 35,
    jailSeconds: 1200,
    jailVarianceSeconds: 180,
    logEvents: true,
  },
}
